# config.py
import os

# Stripe
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# Database
DATABASE_URL = os.getenv("DATABASE_URL")

# Telegram Bots
LETMEBOT_TOKEN = os.getenv("LETMEBOT_TOKEN")
LETMEBOT_PRICE_MONTHLY = os.getenv("LETMEBOT_PRICE_MONTHLY")
LETMEBOT_PRICE_LIFETIME = os.getenv("LETMEBOT_PRICE_LIFETIME")

ONLYTRNS_TOKEN = os.getenv("ONLYTRNS_TOKEN")
ONLYTRNS_PRICE_LIFETIME = os.getenv("ONLYTRNS_PRICE_LIFETIME")

TSWRLDBOT_TOKEN = os.getenv("TSWRLDBOT_TOKEN")
TSWRLDBOT_PRICE_LIFETIME = os.getenv("TSWRLDBOT_PRICE_LIFETIME")

MOREVIDS_TOKEN = os.getenv("MOREVIDS_TOKEN")
MOREVIDS_PRICE_MONTHLY = os.getenv("MOREVIDS_PRICE_MONTHLY")
MOREVIDS_PRICE_LIFETIME = os.getenv("MOREVIDS_PRICE_LIFETIME")
