# config.py
import os

# Stripe
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# Database
DATABASE_URL = os.getenv("DATABASE_URL")

# Telegram Bots Tokens
LETMEBOT_TOKEN = os.getenv("LETMEBOT_TOKEN")
MOREVIDS_TOKEN = os.getenv("MOREVIDS_TOKEN")
ONLYTRNS_TOKEN = os.getenv("ONLYTRNS_TOKEN")
TSWRLDBOT_TOKEN = os.getenv("TSWRLDBOT_TOKEN")

# Stripe Price IDs
LETMEBOT_PRICE_MONTHLY = os.getenv("LETMEBOT_PRICE_MONTHLY")
LETMEBOT_PRICE_LIFETIME = os.getenv("LETMEBOT_PRICE_LIFETIME")
MOREVIDS_PRICE_MONTHLY = os.getenv("MOREVIDS_PRICE_MONTHLY")
MOREVIDS_PRICE_LIFETIME = os.getenv("MOREVIDS_PRICE_LIFETIME")
ONLYTRNS_PRICE_LIFETIME = os.getenv("ONLYTRNS_PRICE_LIFETIME")
TSWRLDBOT_PRICE_LIFETIME = os.getenv("TSWRLDBOT_PRICE_LIFETIME")

# Portal Return URLs
LETMEBOT_PORTAL_RETURN_URL = os.getenv("LETMEBOT_PORTAL_RETURN_URL")
MOREVIDS_PORTAL_RETURN_URL = os.getenv("MOREVIDS_PORTAL_RETURN_URL")
ONLYTRNS_PORTAL_RETURN_URL = os.getenv("ONLYTRNS_PORTAL_RETURN_URL")
TSWRLDBOT_PORTAL_RETURN_URL = os.getenv("TSWRLDBOT_PORTAL_RETURN_URL")

# Channel and Admin
CHANNEL_ID = os.getenv("CHANNEL_ID")
ADMIN_USER_ID = os.getenv("ADMIN_USER_ID")

# Crypto and PayPal (from env)
CRYPTO_ADDRESS = os.getenv("CRYPTO_ADDRESS")
CRYPTO_QR_URL = os.getenv("CRYPTO_QR_URL")

PAYPAL_LETME_MONTHLY = os.getenv("PAYPAL_LETME_MONTHLY")
PAYPAL_LETME_LIFETIME = os.getenv("PAYPAL_LETME_LIFETIME")
PAYPAL_MOREVIDS_MONTHLY = os.getenv("PAYPAL_MOREVIDS_MONTHLY")
PAYPAL_MOREVIDS_LIFETIME = os.getenv("PAYPAL_MOREVIDS_LIFETIME")
PAYPAL_ONLYTRNS = os.getenv("PAYPAL_ONLYTRNS")
PAYPAL_TSWRLD = os.getenv("PAYPAL_TSWRLD")

# Welcome Videos
WELCOME_VIDEO_MOREVIDS = os.getenv("WELCOME_VIDEO_MOREVIDS")
WELCOME_VIDEO_ONLYTRNS = os.getenv("WELCOME_VIDEO_ONLYTRNS")
WELCOME_VIDEO_TSWRLD = os.getenv("WELCOME_VIDEO_TSWRLD")

# Render External URL (추가: Render 배포 URL)
RENDER_EXTERNAL_URL = os.getenv("RENDER_EXTERNAL_URL")

# config.py (파일 끝부분에 추가)

PLAN_PRICES = {
    'letmebot': {'monthly': '$20', 'lifetime': '$50'},
    'morevids': {'monthly': '$20', 'lifetime': '$50'},
    'onlytrns': {'lifetime': '$25'},
    'tswrld': {'lifetime': '$21'},
}
